### ISSUE TITLE
Many "null" in description of this package!

### ISSUE THREAD

**Issue by Nokia808** [flathub/org.mozilla.Firefox.BaseApp#10]
He. I noticed that there is many "null" in the description of this package on GNOME software - see screenshot:

![3](https://user-images.githubusercontent.com/25375330/78650527-91900980-78ae-11ea-8023-8551b4aa789e.png)

**Comment by barthalion** [comment]
This is not the place for such reports. Either way it will be fixed during next push from Mozilla.
