### ISSUE TITLE
[Question] What about firefox add-ons ?

### ISSUE THREAD

**Issue by Nokia808** [flathub/org.mozilla.Firefox.BaseApp#11]
I would like to ask: can add-ons of Firefox installed on this flatpak package in the usual way as any other package like official package or .rpm package (I mean by enter to official add-on page & install needed add-on by click on "install" option from that page).

It will be very disappointing if this not possible.

**Comment by bilelmoussaoui** [comment]
You can install the add-ons from Firefox's addons page but not from distro packages. Also, that's not the place to ask such questions

**Comment by Nokia808** [comment]
@bilelmoussaoui 
Many thanks for this excellent work !
You did not inform me: where this issue should be post ? It is a flatpak issue related to specific flatpak package ! So, where should be posted if not in the repository specific package that related to the issue ?

**Comment by bilelmoussaoui** [comment]
Firefox is who maintains the flatpak, so in their bug tracker.
