### ISSUE TITLE
Firefox won't launch

### ISSUE THREAD

**Issue by Charadon** [flathub/org.mozilla.Firefox.BaseApp#7]
I get this error:
`bwrap: execvp pcsc-spy: No such file or directory`
If I had to take a guess, a dependency is missing.

**Comment by Erick555** [comment]
Can't reproduce. `pcsc-spy` definitely exist in `/app/bin` but I don't know why it would matter. Anyway this isn't a place to report bugs for firefox flatpak, you may try [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1441922)
