### ISSUE TITLE
Broken icon for Firefox in GNOME software

### ISSUE THREAD

**Issue by Nokia808** [flathub/org.mozilla.Firefox.BaseApp#8]
Hi. While Firefox started to appear in GNOME software, I noticed that it's icon is broken - see screenshot:

![1](https://user-images.githubusercontent.com/25375330/78649584-2b56b700-78ad-11ea-8f65-50b8c76c5aa9.png)

**Comment by barthalion** [comment]
This is not the place for such reports. Either way it will be fixed during next push from Mozilla.

**Comment by Nokia808** [comment]
@barthalion 
Where can I post such report ?
