### ISSUE TITLE
2 entries for Firefox on GNOME software

### ISSUE THREAD

**Issue by Nokia808** [flathub/org.mozilla.Firefox.BaseApp#9]
Hi. I noticed that, currently, there are 2 entries for Firefox in GNOME software: one for flatpak package from FlatHub - see screenshot bellow:

![2](https://user-images.githubusercontent.com/25375330/78649935-b5068480-78ad-11ea-8cf3-f0bc4fcc1a39.png)

One entry to flatpak package from FlatHub & 2nd for .rpm package from official Fedora repositories.

The correct thing is that only one entry appear for Firefox, & when click on it there should upper in upper right corner of GNOME software an option to select source (FlatHub or system .rpm package ....). I noticed that not only Firefox suffer from this, but many other packages. I think this related to application ID or something like this ?

**Comment by barthalion** [comment]
There's nothing we can do about it as it's other distributions that are using wrong application ID, not us.

**Comment by Nokia808** [comment]
@barthalion 
Okay. I understood now from where the error & to whom I should report the error. Thank you.
